stages:
    - deploy

deploy_be:
    stage: deploy
    only:
        refs:
            - staging
        changes:
            - "backend/**/*"
    script:
        - git remote rm heroku-be-app || true
        - git remote add heroku-be-app https://heroku:$HEROKU_API_KEY@git.heroku.com/infosupport-2-backend.git || true
        - git subtree split --prefix -b splitting-staging-be
        - git push --force heroku-be-app splitting-staging-be:development
        - git branch -D splitting-staging-be
